### ISSUE TITLE
Good way of seeing mod logs?

### ISSUE THREAD

**Issue by AlixPlayzz** [jagrosh/Vortex#111]
This might already exist. But I can't find it anywhere.

Long story short I want to have a way of seeing ALL a users logs. This includes how many past mutes and bans and the reasons for said mutes and bans, warnings/strikes etc etc. Like dyno has done it:
https://i.imgur.com/KmdpjBc.png

For vortex this is all that I could figure out how to do, and it's driving me nuts. Because I barely get any information and the users modlogs.
https://i.imgur.com/EvGy5To.png

Thanks for any help - Alex

**Comment by jagrosh** [comment]
Vortex does not store this information. You can export all of the data Vortex has about your server via the `>>export` command. Any info not there is only available within logs within Discord channels.

**Comment by AlixPlayzz** [comment]
but why?? that seems really stupid. every other moderation bot does this. why does vortex

**Comment by AlixPlayzz** [comment]
doesn't* ^

**Comment by jagrosh** [comment]
I would not recommend using a bot that you think is stupid, so I would recommend that you use a different bot. Vortex is intentionally built around being fast, scalable and non-redundant. There is no reason to redundantly store mostly read-only data that Discord already stores twice (once in the audit log, and once in the mod log if you have that enabled).

**Comment by AlixPlayzz** [comment]
Okay, fair enough. I just wanted to know a reason, so thanks :D
