### ISSUE TITLE
discord banlist toggle

### ISSUE THREAD

**Issue by untuned** [jagrosh/Vortex#12]
have a toggle to automatically ban users in the discord banlist, and maybe an exemption command to allow someone to join anyway

api: https://bans.discordlist.net/docs

**Comment by TheMonitorLizard** [comment]
That list is bias and run by corrupt individuals.
It will not be supported

**Comment by jagrosh** [comment]
This will never be added.

One of the items on the [Things that won't be added](https://github.com/jagrosh/Vortex/wiki/Things-that-won't-be-added) page is a global ban list.

Next, I would _certainly_ not add support for _that_ ban list. That particular ban list is owned by an individual that breaks Discord's terms of service on many occasions, including mass-spamming advertisement for his services, collecting and releasing end-user data without consent, and has been known to scam groups for his own personal gain. I would never ever trust any service provided by him.
