### ISSUE TITLE
Have an option to be able to assign a already existing mute role

### ISSUE THREAD

**Issue by CJNelsza917** [jagrosh/Vortex#120]
You can't assign a already existing muted role you have to make a mute role specifically for the bot I feel you should just type setup muterole then what role you currently have is the one that's assigned not have to have 500 mute roles for each bot you have in your server

**Comment by NicholasK516** [comment]
This is already a feature. You can use an already existing muted role but it has to be named `Muted` or else Vortex will not detect it.

**Comment by jagrosh** [comment]
This has been possible for a few months now
