### ISSUE TITLE
Developer help

### ISSUE THREAD

**Issue by MRJ-Badshah** [jagrosh/Vortex#125]
Pls create a start run script for selfhosting

**Comment by bup0441** [comment]
you're on your own for running your own instance of Vortex, as it says at the bottom of the README

**Comment by MRJ-Badshah** [comment]
But pls say a run cmd

**Comment by haydenwalker980** [comment]
So uh
- You need an old h2 database version
- you need to know how to write an application.conf file with the library Vortex uses
- you need to implement a bunch of quick 'n dirty fixes  

It's pretty hard but it's possible
