### ISSUE TITLE
Incorrect @everyone detection

### ISSUE THREAD

**Issue by dtomvan** [jagrosh/Vortex#126]
I was muted for using @everyone for Attempted @еveryone/here, which was caused by the following message: `\@everyone`. This triggered the @everyone detection, while I took care not to ping everyone.

**Comment by dtomvan** [comment]
Hmm, that's just weird, how would you type @everyone without pinging?

**Comment by Sanduhr32** [comment]
You don't, or in ``@everyone``

**Comment by dtomvan** [comment]
I guess this is an issue with Discord, not Vortex.
