### ISSUE TITLE
Misuse of Ban Command

### ISSUE THREAD

**Issue by apidev234** [jagrosh/Vortex#127]
The Ban command allows to mass ban all mentioned users which can spam the discord api/raid a server who gets malicious perms. Either give a option to disable the command or put a 30s cooldown

**Comment by jagrosh** [comment]
The command is functioning as intended. The command does not spam the Discord API, as it respects all of the proper ratelimit headers. It does not bypass any permissions, as the Ban permission (or the Moderator role, assigned by an admin) is required to use the command. It also does not bypass the permission hierarchy, as the executor of the command must have a role above all users they are trying to ban.

Do not use Vortex if you do not trust your moderators; Vortex is intended to give **more** power to your moderators and allow them to do tasks more efficiently.
