### ISSUE TITLE
[Bug] autodehoist is dehoisting people because their username starts with a period

### ISSUE THREAD

**Issue by ALocked1** [jagrosh/Vortex#153]
While autodehoist is enabled, it is dehoisting people because of their username due to it's current inability to see display names.

![image](https://github.com/jagrosh/Vortex/assets/60046777/d0d22e26-b4f7-4814-8a1a-0815da6f374b)

**Comment by jagrosh** [comment]
Duplicate (effectively) of #155 (once Vortex can see Display Names, this will be resolved)
