### ISSUE TITLE
AutoMod is not working

### ISSUE THREAD

**Issue by arch-herobrine** [jagrosh/Vortex#158]
AutoMod does not work if `>>serverinfo` is prefixed to the message(Messages are not erased)

<img width="388" alt="スクリーンショット 2023-09-01 144120" src="https://github.com/jagrosh/Vortex/assets/112319383/f61b68df-b86b-43d1-955f-4ce7720f8125"></br>
(The responce of `>>serverinfo` is shown below this image)

(translated by [deepl](https://www.deepl.com/translator))

**Comment by arch-herobrine** [comment]
(I used a translation, so there may be some ambiguity in the wording)

**Comment by jagrosh** [comment]
Automod doesn't apply to people who have elevated permissions; the use of the command is unrelated here.

**Comment by arch-herobrine** [comment]
The image I just posted was taken to recreate the situation. In fact, a user without server admin rights was actually trolling on another server using the same technique as in the image (I forgot to take a screenshot).

原文 : 先ほど貼った画像は状況を再現するために撮ったものです。実際に別のサーバーでサーバー管理権限を持っていないユーザーが同様の手口でトロール行為をしていました。

**Comment by arch-herobrine** [comment]
Here is a video posted by the person who committed the trolling act

https://cdn.discordapp.com/attachments/1141651714198470707/1146010627924566056/Clipchamp_30.mp4
