### ISSUE TITLE
Leaving Servers

### ISSUE THREAD

**Issue by Tritium99** [jagrosh/Vortex#36]
Whatever server I invite Vortex to, it just leaves automatically after a matter of a couple minutes, can't even use one command before it automatically leaves the server! Plus, the bot can't be invited at the moment (its probably down, but I had to say)

**Comment by jagrosh** [comment]
Vortex will leave your server if your server does not meet the minimum requirements outlined on the [wiki](https://github.com/jagrosh/Vortex/wiki).
