### ISSUE TITLE
Anti mention

### ISSUE THREAD

**Issue by luissuniga** [jagrosh/Vortex#4]
Why does it have to be 6 mentions? it's annoying decrease it to 3 mentions ...

**Comment by ArtutoGamer** [comment]
Because raiders usually dont just mention 3-4 people, that would be like a normal message mentioning your friends or smth.
They mass ping people... Or thats what I think...

**Comment by luissuniga** [comment]
A mention is a mention and mentioning 3 or more times in a row is still annoying raider or not

**Comment by jagrosh** [comment]
I'll consider lowering the minimum in Vortex 2.0

**Comment by jagrosh** [comment]
The minimum in the original was set high enough that people cound't accidentally set it too low and be banning people by mistake. With the new 2.0 strikes system, it uses the difference in number of mentions, so allowing a lower number is feasible.

**Comment by luissuniga** [comment]
Thanks, i'll be closing it then.
