### ISSUE TITLE
cant invite the bot

### ISSUE THREAD

**Issue by MBHomeservice** [jagrosh/Vortex#57]
Hello, I wanted to invite your Vortex bot to my Discord Server today but I always get the message that the bot is private and only the owner can invite it. Is the bot no longer accessible to the public?
![info](https://user-images.githubusercontent.com/32205105/79863633-617d5600-83d8-11ea-99b0-e8a845815152.jpg)

**Comment by jagrosh** [comment]
![image](https://user-images.githubusercontent.com/12754382/79867345-38df6700-83ac-11ea-9698-cc5f00ba2cb3.png)
