### ISSUE TITLE
>>setup isn't working 

### ISSUE THREAD

**Issue by sirioth** [jagrosh/Vortex#6]
it doesn't even reply

**Comment by ringmatthew** [comment]
You using this command with [Beta](https://discordapp.com/oauth2/authorize?client_id=169463754382114816&scope=bot&permissions=500559086), right? Furthermore, can you make sure that it has proper permissions in that channel (you can easily guarantee this by giving it the administrator permission)?

**Comment by sirioth** [comment]
No, i'm using it with Vortex lol and it already come with adm permissions

**Comment by ringmatthew** [comment]
That command isn't on Vortex yet. I would recommend you invite Beta too, which is the beta version of Vortex 2.0.

**Comment by sirioth** [comment]
Okay thanks
