### ISSUE TITLE
The checks about 30 human users dont work when you readd the bot after it leaves

### ISSUE THREAD

**Issue by cheesycod** [jagrosh/Vortex#67]
The checks about 30 human users dont work when you readd the bot after it leaves

**Comment by jagrosh** [comment]
It does work, but Vortex doesn't leave servers that have automod or punishment settings set up, so if you are knowledgeable about how to use the bot, it may be possible to bypass the requirement.

**Comment by cheesycod** [comment]
thank you for sharing how to hack the bot
