### ISSUE TITLE
Allow users to get a role using a command

### ISSUE THREAD

**Issue by adrianjmejias** [jagrosh/Vortex#68]
A use case for this could be, for example.

I as a server admin, I would like to set every channel private for everyone.
All channels but one, this channel provides server rules and etiquette, at the end It would hand the users a command to access the server functionality.

for example:
When users type  `>>ireadtherules` they are given a role and are now able to access all the server's channels

**Comment by jagrosh** [comment]
This is listed on the [things that won't be added](https://github.com/jagrosh/Vortex/wiki/Things-that-won't-be-added) page.
