### ISSUE TITLE
Vortex pro

### ISSUE THREAD

**Issue by P2468** [jagrosh/Vortex#75]
Vortex pro is not available

**Comment by P2468** [comment]
If vortex pro is not available, why make them need it to use the feature 

_think about it_

**Comment by jagrosh** [comment]
Because the feature exists, but the infrastructure for allowing people to subscribe to Vortex Pro does not.

**Comment by P2468** [comment]
So why not make it

**Comment by jagrosh** [comment]
I will eventually, when I have time
