### ISSUE TITLE
Guild join date/index incorrect

### ISSUE THREAD

**Issue by relative** [jagrosh/Vortex#76]
In `!userinfo` there is a join index next to the guild join date/date and it appears to be incorrect
![Image](https://xc.mk/d4dDF59.png)

It appears that it adds a `"1"` to the end of the index rather than treating it as an integer.
As far as I can tell the problem is [here](https://github.com/jagrosh/Vortex/blob/a91fbdc42ef5458b90d91926b173414f76bd3570/src/main/java/com/jagrosh/vortex/commands/general/UserinfoCmd.java#L105)?

**Comment by Sanduhr32** [comment]
This is incorrect. Java has type safety so native.int + 1 always calls Integer.plus(1)

**Comment by relative** [comment]
I see that but I don't see any other explanation for why my server which never had 1k+ members is showing incorrect join orders

**Comment by jagrosh** [comment]
Yes, this is a known issue that is already solved [in this commit](https://github.com/jagrosh/Vortex/commit/a91fbdc42ef5458b90d91926b173414f76bd3570#diff-6eeb3b6fc13df42c3f5c057b94518d01e34ef006e6bf5b93ebe20f51a3f4781eR105), I just haven't restarted the bot since fixing it.

**Comment by relative** [comment]
> Yes, this is a known issue that is already solved [in this commit](https://github.com/jagrosh/Vortex/commit/a91fbdc42ef5458b90d91926b173414f76bd3570#diff-6eeb3b6fc13df42c3f5c057b94518d01e34ef006e6bf5b93ebe20f51a3f4781eR105), I just haven't restarted the bot since fixing it.

Makes sense, sorry for the false alarm
