### ISSUE TITLE
How to set up anti spam on Beta?

### ISSUE THREAD

**Issue by sirioth** [jagrosh/Vortex#8]
when i use ((setup it doesn't have AutoMod option and neither any command to enable anti spam

**Comment by jagrosh** [comment]
I believe you are looking for Anti-Duplicate, which can be setup via the [automod commands](https://github.com/jagrosh/Vortex/wiki/Commands#-automod-commands).

**Comment by jagrosh** [comment]
Also, the issue tracker is only for bug reports and feature requests; for questions please ask in [my development server](https://discord.gg/0p9LSGoRLu6Pet0k)
