### ISSUE TITLE
Add the ability to see the list of people who have strikes.

### ISSUE THREAD

**Issue by tanzaa** [jagrosh/Vortex#84]
I've been moderating in a big server and giving strikes to many people andwe have a rule that said "we may remove strikes if the user in question improved their behaviour over a certain amount of time"
Now the problem is that we have more than **200+ people** who recieved strikes and,you know, we won't go through all the logs to see it individually.
So It would be a great idea to see the whole list of people who recieve a strike.

**Comment by jagrosh** [comment]
You can use the `>>export` command to get all of the data Vortex has stored about your server, which includes strike counts for every user that has strikes. A separate command to show this will probably not be added, as there's not a good way to present that information concisely, so the file output is the ideal system anyway.
