### ISSUE TITLE
im possibly cursed

### ISSUE THREAD

**Issue by DipperPines8115** [jagrosh/Vortex#90]
ok, vortex is striking me alot for no reason and im actualy about to get banned forever from a server and i should actualy have about 3 strikes

i once got striked for 3 strikes for sending a GIF

if u can please check if there its true that vortex does sign me as "cursed" or somthing then can u please dm my discord: _DipperPines#8115 that i am cursed and if u can please all of my strikes but the ones i got from staff and the one i did @everyone(talking to the devs)

even if im not just dm me that im not(still talking to the devs)

**Comment by jagrosh** [comment]
Vortex does not behave differently towards different users; check the reason that Vortex provides in a DM when you get striked to see why you received the strike.

**Comment by DipperPines8115** [comment]
i sent gifs
and he striked me for toxic and rude
3 strikes
for sending a gif
as a joke
breh

**Comment by DipperPines8115** [comment]
and some1 asked if he can join a certain discord server
so i sent the invite and vortex sent 2 strikes for advertizing
i guess that makes sense but i still just wanted to help the guy
