### ISSUE TITLE
How to stop vortex logging messages in a private channel?

### ISSUE THREAD

**Issue by j95854** [jagrosh/Vortex#95]
I have a private channel on my server that is only accessible to me and the bots, is there a way I can prevent Vortex from logging messages from that channel so my staff can't see deleted and edited messages? I've checked the command list and as far as I can see the logging commands only turn *all* the logs on or off, instead of just ignoring one channel.

**Comment by NicholasK516** [comment]
Deny Vortex the user Read_Message_History in the channel. Not the role though the user itself. If you are wondering why this works is because vortex specifically checks to see if it has read message history even if it has the Administrator Permission.

**Comment by jagrosh** [comment]
I've updated [this page on the wiki](https://github.com/jagrosh/Vortex/wiki/Rarely-Asked-Questions#how-to-prevent-message-logs-from-a-specific-channel) to address this question
