### ISSUE TITLE
setup automod isnt a command now D: 

### ISSUE THREAD

**Issue by ishitajs** [jagrosh/Vortex#98]
Vortex setup automod command isnt working while running even bot has admin perms and have no role hierarchy 
Image: https://cdn.discordapp.com/attachments/185037029384388608/847523317543469111/unknown.png

**Comment by jagrosh** [comment]
Correct, this feature has been removed to encourage servers to only enable features if they are knowledgeable about what the feature does and are intending to enable it. Similarly, there are no punishments that are automatically created; these must also be manually created.

The [automoderation page on the wiki](https://github.com/jagrosh/Vortex/wiki/Auto-Moderation) contains overviews of all automod features, as well as recommended values. Hopefully, this will improve the interactions that users have with automod, as fewer people will get confused by Vortex performing actions that they (indirectly) set up but didn't realize they did.
